export const FETCH_TODO = 'FETCH_TODO';
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
export const FETCH_TODO_FAILED = 'FETCH_TODO_FAILED';
export const FILTER_TODO = 'FILTER_TODO';
export const FILTER_TODO_SUCCESS = 'FILTER_TODO_SUCCESS';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';

export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED';

export const SEARCH_TODO = 'SEARCH_TODO';
export const SEARCH_TODO_SUCCESS = 'SEARCH_TODO_SUCCESS';
export const SEARCH_TODO_FAILED = 'SEARCH_TODO_FAILED';